# Generated by Django 5.2.13 on 2026-05-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="detected_intent",
            field=models.CharField(blank=True, db_index=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="matched_product_name",
            field=models.CharField(blank=True, db_index=True, default="", max_length=300),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="status",
            field=models.CharField(
                choices=[
                    ("normal", "Normal"),
                    ("fallback", "Fallback"),
                    ("rate_limited", "Rate limited"),
                ],
                db_index=True,
                default="normal",
                max_length=20,
            ),
        ),
    ]
