# Generated by Django 5.2.13 on 2026-04-30 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_inventoryitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('restock', 'Restock'), ('adjustment', 'Manual Adjustment'), ('damaged', 'Damaged / Written Off'), ('return', 'Customer Return')], max_length=20)),
                ('quantity_delta', models.IntegerField(help_text='Positive = stock added, Negative = stock removed')),
                ('quantity_before', models.PositiveIntegerField(help_text='Stock level before this movement')),
                ('quantity_after', models.IntegerField(help_text='Stock level after this movement')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='products.inventoryitem')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['inventory_item', '-created_at'], name='products_st_invento_66a28c_idx')],
            },
        ),
    ]
