# Generated by Django 5.2.13 on 2026-04-30 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_stockmovement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StandaloneInventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=300)),
                ('section', models.CharField(default='Uncategorised', max_length=100)),
                ('quantity_in_stock', models.PositiveIntegerField(default=0)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sell_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reorder_level', models.PositiveIntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['section'], name='products_st_section_7dde01_idx'), models.Index(fields=['quantity_in_stock'], name='products_st_quantit_ffc518_idx')],
                'constraints': [models.UniqueConstraint(fields=('name', 'section'), name='unique_standalone_name_section')],
            },
        ),
        migrations.CreateModel(
            name='StandaloneInventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('restock', 'Restock'), ('adjustment', 'Manual Adjustment'), ('damaged', 'Damaged / Written Off'), ('return', 'Customer Return'), ('sale', 'Sale / Dispatch'), ('transfer', 'Transfer'), ('import', 'CSV Import'), ('initial', 'Initial Stock')], max_length=20)),
                ('quantity_delta', models.IntegerField(help_text='Positive = stock added, Negative = stock removed')),
                ('quantity_before', models.PositiveIntegerField(help_text='Stock level before this movement')),
                ('quantity_after', models.IntegerField(help_text='Stock level after this movement')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='products.standaloneinventoryitem')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='standalone_stock_movements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['inventory_item', '-created_at'], name='products_st_invento_a74858_idx')],
            },
        ),
    ]
