# Generated by Django 5.2.13 on 2026-05-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_standaloneinventoryitem_standaloneinventorymovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='company',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='email_sent',
            field=models.BooleanField(default=False, help_text='Set True once Resend emails are dispatched'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='products',
            field=models.JSONField(blank=True, default=list, help_text='List of product names the customer tagged/saved', null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='source_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
