# Generated by Django 5.2.13 on 2026-05-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_add_inquiry_email_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('incremental', 'Incremental (single item)'), ('full', 'Full Sync'), ('delete', 'Row Deletion')], default='incremental', max_length=20)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('partial', 'Partial (some errors)'), ('skipped', 'Skipped (Sheets disabled)')], db_index=True, max_length=20)),
                ('items_synced', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('triggered_by', models.CharField(choices=[('signal', 'Auto (DB Signal)'), ('manual', 'Manual (Sync Now)'), ('bulk_import', 'Bulk CSV Import')], default='signal', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='products_sy_status_e179c5_idx'), models.Index(fields=['triggered_by', '-created_at'], name='products_sy_trigger_b97a2e_idx')],
            },
        ),
    ]
