# Generated by Django 5.2.13 on 2026-05-11 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def populate_standalone_skus(apps, schema_editor):
    StandaloneInventoryItem = apps.get_model("products", "StandaloneInventoryItem")
    for item in StandaloneInventoryItem.objects.filter(sku="").order_by("id"):
        item.sku = f"FSI-{item.pk:06d}"
        item.save(update_fields=["sku"])


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_add_synclog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_name = 'products_standaloneinventoryitem'
                      AND column_name = 'sku'
                ) THEN
                    DROP INDEX IF EXISTS products_standaloneinventoryitem_sku_8dea7cad;
                    DROP INDEX IF EXISTS products_standaloneinventoryitem_sku_8dea7cad_like;
                END IF;
            END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddField(
            model_name="standaloneinventoryitem",
            name="sku",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="standaloneinventoryitem",
            name="unit",
            field=models.CharField(default="unit", max_length=30),
        ),
        migrations.RunPython(populate_standalone_skus, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="standaloneinventoryitem",
            name="sku",
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
        migrations.CreateModel(
            name="InventorySyncJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("scope", models.CharField(choices=[("standalone", "Standalone Inventory"), ("product", "Product Inventory"), ("system", "System-wide")], max_length=20)),
                ("operation", models.CharField(choices=[("upsert", "Upsert Row"), ("batch_upsert", "Batch Upsert Rows"), ("delete", "Delete Row"), ("full_sync", "Full Sync")], max_length=20)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("processing", "Processing"), ("retry", "Retry Scheduled"), ("success", "Success"), ("failed", "Failed"), ("skipped", "Skipped"), ("cancelled", "Cancelled")], db_index=True, default="pending", max_length=20)),
                ("triggered_by", models.CharField(choices=[("signal", "Auto (DB Signal)"), ("manual", "Manual (Sync Now)"), ("bulk_import", "Bulk CSV Import")], db_index=True, default="signal", max_length=20)),
                ("item_key", models.CharField(blank=True, db_index=True, default="", help_text="Stable spreadsheet row identifier, typically the SKU.", max_length=100)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("max_attempts", models.PositiveSmallIntegerField(default=5)),
                ("last_error", models.TextField(blank=True, default="")),
                ("next_attempt_at", models.DateTimeField(db_index=True, default=timezone.now)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("requested_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="inventory_sync_jobs", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(fields=["status", "next_attempt_at"], name="products_in_status_dfb658_idx"),
                    models.Index(fields=["scope", "item_key", "status"], name="products_in_scope_9bd4f5_idx"),
                    models.Index(fields=["triggered_by", "created_at"], name="products_in_trigger_0f3d67_idx"),
                ],
            },
        ),
    ]
