# Generated by Django 5.2.13 on 2026-05-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_standalone_sku_and_sync_jobs'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='inventorysyncjob',
            new_name='products_in_status_ea77d7_idx',
            old_name='products_in_status_dfb658_idx',
        ),
        migrations.RenameIndex(
            model_name='inventorysyncjob',
            new_name='products_in_scope_ff5e85_idx',
            old_name='products_in_scope_9bd4f5_idx',
        ),
        migrations.RenameIndex(
            model_name='inventorysyncjob',
            new_name='products_in_trigger_bc2283_idx',
            old_name='products_in_trigger_0f3d67_idx',
        ),
        migrations.AlterField(
            model_name='synclog',
            name='sync_type',
            field=models.CharField(choices=[('incremental', 'Incremental Sync'), ('full', 'Full Sync'), ('delete', 'Row Deletion')], default='incremental', max_length=20),
        ),
    ]
