# Generated by Django 5.2.13 on 2026-05-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_rename_products_in_status_dfb658_idx_products_in_status_ea77d7_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='google_sheet_row_id',
            field=models.PositiveIntegerField(blank=True, help_text='1-based row number in the Google Sheet.', null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='sync_status',
            field=models.CharField(blank=True, default='', help_text="Last sync result: 'success', 'failure', or empty.", max_length=20),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='synced_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last successful Google Sheets sync.', null=True),
        ),
        migrations.AddField(
            model_name='standaloneinventoryitem',
            name='google_sheet_row_id',
            field=models.PositiveIntegerField(blank=True, help_text='1-based row number in the Google Sheet.', null=True),
        ),
        migrations.AddField(
            model_name='standaloneinventoryitem',
            name='sync_status',
            field=models.CharField(blank=True, default='', help_text="Last sync result: 'success', 'failure', or empty.", max_length=20),
        ),
        migrations.AddField(
            model_name='standaloneinventoryitem',
            name='synced_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last successful Google Sheets sync.', null=True),
        ),
    ]
