# Generated by Django 5.2.15 on 2026-07-07 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_add_sync_metadata_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, default='', max_length=300)),
                ('meta_description', models.CharField(blank=True, default='', max_length=500)),
                ('focus_keyword', models.CharField(blank=True, default='', max_length=200)),
                ('secondary_keywords', models.JSONField(blank=True, default=list)),
                ('long_tail_keywords', models.JSONField(blank=True, default=list)),
                ('introduction', models.TextField(blank=True, default='')),
                ('features', models.JSONField(blank=True, default=list)),
                ('benefits', models.JSONField(blank=True, default=list)),
                ('technical_specifications', models.JSONField(blank=True, default=dict)),
                ('applications', models.JSONField(blank=True, default=list)),
                ('industries_served', models.JSONField(blank=True, default=list)),
                ('delivery_locations', models.JSONField(blank=True, default=list)),
                ('faqs', models.JSONField(blank=True, default=list)),
                ('cta_text', models.TextField(blank=True, default='')),
                ('internal_links', models.JSONField(blank=True, default=list)),
                ('product_schema', models.JSONField(blank=True, default=dict)),
                ('faq_schema', models.JSONField(blank=True, default=dict)),
                ('breadcrumb_schema', models.JSONField(blank=True, default=dict)),
                ('organization_schema', models.JSONField(blank=True, default=dict)),
                ('image_seo_filename', models.CharField(blank=True, default='', max_length=255)),
                ('image_alt_text', models.CharField(blank=True, default='', max_length=255)),
                ('image_title', models.CharField(blank=True, default='', max_length=255)),
                ('image_caption', models.CharField(blank=True, default='', max_length=500)),
                ('image_description', models.TextField(blank=True, default='')),
                ('score_overall', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('score_breakdown', models.JSONField(blank=True, default=dict)),
                ('is_optimized', models.BooleanField(db_index=True, default=False)),
                ('draft', models.JSONField(blank=True, default=None, null=True)),
                ('ai_model_used', models.CharField(blank=True, default='', max_length=100)),
                ('ai_generation_meta', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seo_drafts_generated', to=settings.AUTH_USER_MODEL)),
                ('last_published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seo_drafts_published', to=settings.AUTH_USER_MODEL)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seo', to='products.product')),
            ],
            options={
                'indexes': [models.Index(fields=['score_overall'], name='products_pr_score_o_d633bc_idx'), models.Index(fields=['published_at'], name='products_pr_publish_348d34_idx')],
            },
        ),
        migrations.CreateModel(
            name='SEOVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('reason', models.CharField(choices=[('pre_apply', 'Before Apply'), ('pre_restore', 'Before Restore')], max_length=20)),
                ('snapshot', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seo_versions_created', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seo_versions', to='products.product')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', '-created_at'], name='products_se_product_c0abf4_idx')],
            },
        ),
    ]
