# Generated by Django 5.2.15 on 2026-07-07 15:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_add_seo_regeneration_job'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WatermarkBulkControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(db_index=True, max_length=40, unique=True)),
                ('is_paused', models.BooleanField(default=False)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageProtectionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watermark_enabled', models.BooleanField(default=False)),
                ('right_click_protection_enabled', models.BooleanField(default=False)),
                ('drag_protection_enabled', models.BooleanField(default=False)),
                ('long_press_protection_enabled', models.BooleanField(default=False)),
                ('seo_metadata_protection_enabled', models.BooleanField(default=False)),
                ('watermark_text', models.CharField(default='FINSTAR INDUSTRIAL SYSTEMS LTD', max_length=200)),
                ('watermark_secondary_text', models.CharField(default='www.finstarsystems.co.ke', max_length=200)),
                ('watermark_opacity', models.PositiveSmallIntegerField(default=20, help_text='Percent opacity (1-100). Recommended: 15-25.')),
                ('watermark_font_size', models.PositiveSmallIntegerField(default=48, help_text='Base font size in px, scaled by Cloudinary per image.')),
                ('watermark_angle', models.SmallIntegerField(default=-45, help_text='Rotation angle in degrees (-90 to 90).')),
                ('watermark_position', models.CharField(choices=[('center', 'Centered (single)'), ('tiled', 'Repeated diagonal pattern')], default='tiled', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_protection_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Image protection settings',
                'verbose_name_plural': 'Image protection settings',
            },
        ),
        migrations.CreateModel(
            name='ProductImageProtection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_watermark_applied', models.BooleanField(db_index=True, default=False)),
                ('watermark_applied_at', models.DateTimeField(blank=True, null=True)),
                ('last_restored_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image_protection', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ImageProtectionAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('settings_changed', 'Settings Changed'), ('watermark_applied', 'Watermark Applied'), ('watermark_removed', 'Watermark Removed'), ('bulk_started', 'Bulk Job Started'), ('bulk_paused', 'Bulk Job Paused'), ('bulk_resumed', 'Bulk Job Resumed'), ('bulk_cancelled', 'Bulk Job Cancelled'), ('restore_single', 'Single Product Restored'), ('restore_all', 'All Products Restored')], db_index=True, max_length=30)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_protection_audit_entries', to='products.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_protection_audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', '-created_at'], name='products_im_action_0cd555_idx')],
            },
        ),
        migrations.CreateModel(
            name='WatermarkJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(db_index=True, max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=3)),
                ('next_attempt_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_error', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watermark_jobs', to='products.product')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='watermark_bulk_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['batch_id', 'status'], name='products_wa_batch_i_b621b8_idx'), models.Index(fields=['status', 'next_attempt_at'], name='products_wa_status_289c90_idx')],
            },
        ),
    ]
