# Generated by Django 5.2.16 on 2026-07-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_add_seo_issues_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='productseo',
            name='canonical_url',
            field=models.URLField(blank=True, default='', help_text='Canonical URL for the page'),
        ),
        migrations.AddField(
            model_name='productseo',
            name='indexed',
            field=models.BooleanField(default=False, help_text='Whether the page is indexed by search engines'),
        ),
        migrations.AddField(
            model_name='productseo',
            name='last_crawled',
            field=models.DateTimeField(blank=True, help_text='When search engines last crawled the page', null=True),
        ),
        migrations.AddField(
            model_name='productseo',
            name='schema_score',
            field=models.PositiveSmallIntegerField(default=0, help_text='Score representing schema completeness and validity (0-100)'),
        ),
    ]
