# Generated by Django 5.2.15 on 2026-07-09 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_productseo_canonical_url_productseo_indexed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productseo',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Canonical URL for SEO purposes'),
        ),
        migrations.AlterField(
            model_name='productseo',
            name='schema_score',
            field=models.PositiveSmallIntegerField(default=0, help_text='Score indicating completeness/validity of schema markup (0-100)'),
        ),
    ]
