# Generated by Django 5.2.16 on 2026-07-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_productseo_canonical_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Manufacturer/OEM brand (e.g. Danfoss, Riello) — NOT Finstar, the reseller.', max_length=150),
        ),
    ]
