# Generated by Django 5.2.15 on 2026-07-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='seoregenerationjob',
            name='auto_publish',
            field=models.BooleanField(default=False, help_text='If true, a completed job publishes live automatically when it clears the score gate.'),
        ),
        migrations.AddField(
            model_name='seoregenerationjob',
            name='publish_block_reason',
            field=models.TextField(blank=True, default='', help_text="Why an auto_publish job's content was held as a draft instead of published, if it was."),
        ),
        migrations.AddField(
            model_name='seoregenerationjob',
            name='published',
            field=models.BooleanField(default=False, help_text="Whether this job's generated content actually went live (only possible when auto_publish=True)."),
        ),
    ]
